experiment_dir: /N/scratch/jmelms/ML_atmos_model_conservation_tests_scratch_data/B.energy_balance/data
experiment_name: SFNO_xr_unperturbed_small
ic_type: "xr"
ic_dates: ['2018-02-01T00z']
xr_file: /N/slate/jmelms/projects/IC/E3SM/unperturbed/SFNO_pert=False.nc
models: ["SFNO"]
n_timesteps: 8
device: cuda:0
debug_run: False
overwrite: True # change to false!
surface_geopotential_path: "/N/slate/jmelms/projects/ML_atmos_model_conservation_tests/A.mass_conservation/surface_geopotential.nc"
keep_base_fields: True
temp_perturbation_degC: 0
balance_perturbation: True
upert_e3sm_paths: [
  "/N/slate/jmelms/projects/ML_atmos_model_conservation_tests/B.energy_balance/data/E3SM_runs/v2.1.WCYCLSSP370_20180201-20180401_12n32p_original_20260114/run/v2.1.WCYCLSSP370_20180201-20180401_12n32p_original_20260114.eam.h1.2018-02-01-00000.nc",
  "/N/slate/jmelms/projects/ML_atmos_model_conservation_tests/B.energy_balance/data/E3SM_runs/v2.1.WCYCLSSP370_20180201-20180401_12n32p_original_20260114/run/v2.1.WCYCLSSP370_20180201-20180401_12n32p_original_20260114.eam.h1.2018-03-03-00000.nc"
]
pert_e3sm_paths: [
  "/N/slate/jmelms/projects/ML_atmos_model_conservation_tests/B.energy_balance/data/E3SM_runs/v2.1.WCYCLSSP370_20180201-20180401_12n32p_trial_07/run/v2.1.WCYCLSSP370_20180201-20180401_12n32p_trial_07.eam.h1.2018-02-01-00000.nc",
  "/N/slate/jmelms/projects/ML_atmos_model_conservation_tests/B.energy_balance/data/E3SM_runs/v2.1.WCYCLSSP370_20180201-20180401_12n32p_trial_07/run/v2.1.WCYCLSSP370_20180201-20180401_12n32p_trial_07.eam.h1.2018-03-03-00000.nc"
  ]
experiment_subdirectories: 
  - "plots"
 