experiment_dir: data/
experiment_name: nt=12_nic=1_NO_GCO
ic_dates: [
  '2020-01-01T00z',
  ]
models: ["FuXi", "SFNO", "Pangu6x"]
n_timesteps: 12
device: cuda:0
debug_run: False
overwrite: True # change to false!
surface_geopotential_path: "/N/slate/jmelms/projects/ML_atmos_model_conservation_tests/A.mass_conservation/surface_geopotential.nc"
keep_base_fields: False
temp_perturbation_degC: 5
experiment_subdirectories: 
  - "plots"
 