experiment_dir: /N/slate/jmelms/projects/ML_atmos_model_conservation_tests/A.mass_conservation/run_ACE2/output
n_forward_steps: 13 # one more than e2s to include IC
forward_steps_in_memory: 50
checkpoint_path: /N/slate/jmelms/projects/ML_atmos_model_conservation_tests/A.mass_conservation/run_ACE2/model_data/ace2_era5_ckpt.tar
logging:
  log_to_screen: true
  log_to_wandb: false
  log_to_file: true
  project: ace
initial_condition:
  path: /N/slate/jmelms/projects/ML_atmos_model_conservation_tests/A.mass_conservation/run_ACE2/model_data/initial_conditions/ic_2020.nc
  start_indices:
    times:
      - "2020-01-01T00:00:00"
      - "2020-07-01T00:00:00"
forcing_loader:
  dataset:
    data_path: /N/slate/jmelms/projects/ML_atmos_model_conservation_tests/A.mass_conservation/run_ACE2/model_data/forcings
  num_data_workers: 1
data_writer:
  save_prediction_files: true
  save_monthly_files: false
  names: [
    # terms for moisture and total energy
    "specific_total_water_0",
    "specific_total_water_1",
    "specific_total_water_2",
    "specific_total_water_3",
    "specific_total_water_4",
    "specific_total_water_5",
    "specific_total_water_6",
    "specific_total_water_7",
    "Q2m", 
    "PRESsfc",
    # terms for just total energy
    "air_temperature_0",
    "air_temperature_1",
    "air_temperature_2",
    "air_temperature_3",
    "air_temperature_4",
    "air_temperature_5",
    "air_temperature_6",
    "air_temperature_7",
    "TMP2m",
    "eastward_wind_0",
    "eastward_wind_1",
    "eastward_wind_2",
    "eastward_wind_3",
    "eastward_wind_4",
    "eastward_wind_5",
    "eastward_wind_6",
    "eastward_wind_7",
    "UGRD10m",
    "northward_wind_0",
    "northward_wind_1",
    "northward_wind_2",
    "northward_wind_3",
    "northward_wind_4",
    "northward_wind_5",
    "northward_wind_6",
    "northward_wind_7",
    "VGRD10m"
    ]
