experiment_dir: data/
experiment_name: test
ic_dates: [
  '2010-01-01T00z',
  '2010-07-01T00z'
  ]
models: ["SFNO"] # and FCNv2_SM
n_timesteps: 10
device: cuda:0
debug_run: False
overwrite: True # change to false!
keep_vars: ["sp", "msl", "ssp"]
surface_geopotential_path: "/N/slate/jmelms/projects/dcmip2025_idealized_tests/experiments/A.mass_conservation/surface_geopotential.nc"
pressure_multiplier: 1.0
keep_base_fields: False
experiment_subdirectories: 
  - "plots"
 